name: Unit tests

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true



jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-20.04
    env:
      extensions: bcmath

    strategy:
      matrix:
        include:
          - php: '8.2'
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          ini-values: date.timezone=UTC,memory_limit=-1
          php-version: "${{ matrix.php }}"
          extensions: "${{ env.extensions }}"
          tools: flex
      - name: Composer
        uses: php-actions/composer@v6
      - name: Run tests
        run: vendor/bin/phpunit tests